### ISSUE TITLE
design: I cannot see the "data documentation" on the website

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-project#155]
I can only see the "Software architecture documentation" folder on the website. Not the "data documentation" folder, "decisions" nor "examples".   

NB: only data documentation is mentioned on the design landing page, design/index.md (if decisions and examples should be included as well).

**Comment by lwjohnst86** [comment]
Yes, that's intentional. Those files aren't ready to be published to the website just yet.
