### ISSUE TITLE
add logo as organisation and/or repo logo? 

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-project#163]
Could be nice if the logo is used here on GitHub as well as on the website :-) / Do we currently have a logo?

**Comment by lwjohnst86** [comment]
Logo from Sprout has been added to the GitHub organization, so at least we have something 😛

**Comment by signekb** [comment]
Nice! It actually looks a bit weird that the green box "doesn't fit" and has a white background bc it's tilted 45 degrees 🤔
