### ISSUE TITLE
C4 Code Diagram

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-project#75]
[Code](https://c4model.com/#CodeDiagram): Diagrams aimed at very technical people, mostly for internal use. Focus should ideally be on the very important or complex components. This will only be a general overview rather than as detailed as suggested by C4, like a very basic flowchart of how data flows through the application (like in the pathways folder). This diagram is more for us to state generally what it should look like and to use as a roadmap to help guide our work.

Low priority right now, but useful to eventually start adding to. It isn't required for the report.

**Comment by signekb** [comment]
This can be done automatically instead. Closing.
